FROM arm32v7/python:3.8-slim

RUN apt-get update -q \
  && apt-get install gcc apt-utils bcrypt inetutils-ping python python-pip python-dev libffi-dev libjpeg-dev zlib1g-dev -y \
  && rm -rf /var/lib/apt/lists/*

COPY [ "requirements.txt", "/dashmachine/" ]

WORKDIR /dashmachine

RUN pip install --no-cache-dir --progress-bar off -r requirements.txt

COPY [ ".", "/dashmachine/" ]

ENV PRODUCTION=true
EXPOSE 5000
VOLUME /dashmachine/dashmachine/user_data
CMD [ "gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app" ]
