version: '2'

services:
    dashmachine:
      image: volcan96/dashmachine-docker-rpi:latest
      restart: unless-stopped
      volumes:
      - /home/pi/dashmachine/_data:/dashmachine/dashmachine/user_data
      ports:
      - 5000:5000
      environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
